[[constraint]]
  name = "github.com/distatus/battery"
  version = "0.9.0"

[[constraint]]
  name = "github.com/docopt/docopt.go"
  branch = "master"

[[constraint]]
  name = "github.com/gizak/termui"
  version = "3.0.0"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  #version = "=2.18.11"
  version = "2.19.05"

[prune]
  go-tests = true
  unused-packages = true
